export const marketplaceVendors = [
    {
        id: "v1",
        name: "Royal Palace Events",
        category: "Venue",
        city: "Jaipur",
        rating: 4.9,
        reviews: 124,
        priceRange: "₹5L - ₹15L",
        image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800",
        description: "A breathtaking heritage venue offering authentic Rajasthani hospitality with grand mandap spaces and lush lawns.",
        featured: true,
    },
    {
        id: "v2",
        name: "The Grand Caterers",
        category: "Catering",
        city: "Mumbai",
        rating: 4.8,
        reviews: 89,
        priceRange: "₹1,500 - ₹3,500 per plate",
        image: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=800",
        description: "Specializing in authentic regional Indian cuisines and international live counters.",
        featured: false,
    },
    {
        id: "v3",
        name: "Lumina Photography",
        category: "Photography",
        city: "Delhi",
        rating: 5.0,
        reviews: 210,
        priceRange: "₹1.5L - ₹4L per day",
        image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=800",
        description: "Award-winning wedding photography duo focusing on candid moments and cinematic storytelling.",
        featured: true,
    },
    {
        id: "v4",
        name: "Elegance Decorators",
        category: "Decoration",
        city: "Udaipur",
        rating: 4.7,
        reviews: 156,
        priceRange: "₹2L - ₹8L",
        image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&q=80&w=800",
        description: "Specialists in theme-based wedding decorations, floral mandaps, and ambient grand lighting.",
        featured: false,
    },
    {
        id: "v5",
        name: "Harmony Planners",
        category: "Planner",
        city: "Goa",
        rating: 4.9,
        reviews: 67,
        priceRange: "₹3L - ₹6L (Fee)",
        image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800",
        description: "Your go-to planners for seamless destination weddings in Goa and Kerala.",
        featured: false,
    },
    {
        id: "v6",
        name: "Makeup by Simran",
        category: "Makeup",
        city: "Mumbai",
        rating: 4.9,
        reviews: 342,
        priceRange: "₹25k - ₹50k per function",
        image: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&q=80&w=800",
        description: "Celebrity makeup artist offering flawless bridal HD makeup and hairstyling.",
        featured: true,
    }
];
